### ISSUE TITLE
Not working for .osm file

### ISSUE THREAD

**Issue by nuriakman** [whizsid/osm-to-sql#1]
I download https://download.geofabrik.de/europe/turkey-latest.osm.bz2 file (in xml format) file from https://download.geofabrik.de/europe/turkey.html

I used this command: `osm-to-sql -i turkey-latest.xml -d myOutputFolder/`

it gives this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 17, kind: AlreadyExists, message: "File exists" }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

What is wrong?

**Comment by whizsid** [comment]
Hy @nuriakman ,
Please make sure the output directory is empty before using this command. Run `rm ./myOutputFolder/*` to empty the folder.

**Comment by nuriakman** [comment]
Problem solved after empty folder. Thank you!

**Comment by whizsid** [comment]
@nuriakman Great to hear it. Thank you for using this tool!
